apiVersion: limitador.kuadrant.io/v1alpha1
kind: RateLimit
metadata:
  name: ratelimit-sample
spec:
  namespace: test_namespace
  max_value: 10
  seconds: 60
  conditions:
    - "req.method == GET"
  variables:
    - user_id
